// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aemgofyievwmexmmduik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlbWdvZnlpZXZ3bWV4bW1kdWlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MjAxODEsImV4cCI6MjA2NDI5NjE4MX0.RwGplrhEO7AeN9gwjmNurrOMqva_2obgtqN0kbPAwMg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);