// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czxybnoovembpdikvtzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6eHlibm9vdmVtYnBkaWt2dHp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NzI1MTIsImV4cCI6MjA2MzE0ODUxMn0.hBgf0SPafsm4ehNYKFQ7FhqX6MHmDLaWULckzI1ddCs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);